---
- name: Drop database config
  template:
    src: "dbconfig.xml.j2"
    dest: "{{ jira_home }}/dbconfig.xml"
    mode: "640"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
  notify: "restart jira{{ ' (systemd)' if ansible_service_mgr == 'systemd' else '' }}"
