---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
platforms:
  - name: jiraserver
    # Subgraph OS is based on Debian Stretch
    box: debian/jessie64
    instance_raw_config_args:
      - "vm.synced_folder '.', '/vagrant', disabled: true"
      - "vm.network 'forwarded_port', guest: 443, host: 4443"
      - "vm.network 'forwarded_port', guest: 80, host: 8080"
    provider_memory: 4096
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
